export default function() {
    return [
        { title: 'Javascript: The Good Parts' },
        { title: 'Harry Potter' },
        { title: 'Winnie The Pooh' },
        { title: 'Mickey Mouse' }
    ]
}

// redux serves to construct the application state and react provides the views to display that state
// two libraries are inherently disconnected and its only through the use of react-redux that we may get a 
// clear connection between the two.
// application state is generated by reducer functions.
// created one reduce called reducer.
// 